services:
  gateway-service:
    image: klnstprx/gateway-service
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./src/backend/config.docker.toml:/app/config.toml
    environment:
      - DOCKER=true
    depends_on:
      - wiki-service
      - entry-service
      - comment-service
      - version-service
      - media-service

  wiki-service:
    image: klnstprx/wiki-service
    networks:
      - app-network
    expose:
      - "8001"
    volumes:
      - ./src/backend/config.docker.toml:/app/config.toml
    environment:
      - DOCKER=true

  entry-service:
    image: klnstprx/entry-service
    networks:
      - app-network
    expose:
      - "8002"
    volumes:
      - ./src/backend/config.docker.toml:/app/config.toml
    environment:
      - DOCKER=true

  comment-service:
    image: klnstprx/comment-service
    networks:
      - app-network
    expose:
      - "8003"
    volumes:
      - ./src/backend/config.docker.toml:/app/config.toml
    environment:
      - DOCKER=true

  version-service:
    image: klnstprx/version-service
    networks:
      - app-network
    expose:
      - "8005"
    volumes:
      - ./src/backend/config.docker.toml:/app/config.toml
    environment:
      - DOCKER=true

  media-service:
    image: klnstprx/media-service
    networks:
      - app-network
    expose:
      - "8081"
    volumes:
      - ./src/backend/config.docker.toml:/app/config.toml
    environment:
      - DOCKER=true

  lawiki-frontend:
    image: klnstprx/lawiki-frontend
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - gateway-service

networks:
  app-network:
    driver: bridge
