[global]
API_GATEWAY_URL = "http://localhost:8000"
DB_NAME = "laWikiCopia2"
PRETTY_LOGS = true
DEBUG = true
MONGODB_URI = ""

[gateway]
PORT = 8000
WIKI_SERVICE_URL = "http://localhost:8001"
ENTRY_SERVICE_URL = "http://localhost:8002"
COMMENT_SERVICE_URL = "http://localhost:8003"
VERSION_SERVICE_URL = "http://localhost:8005"
AUTH_SERVICE_URL = "http://localhost:8080"
MEDIA_SERVICE_URL = "http://localhost:8081"

[wiki]
PORT = 8001
DB_COLLECTION_NAME = "wikis"

[entry]
PORT = 8002
DB_COLLECTION_NAME = "entradas"

[comment]
PORT = 8003
DB_COLLECTION_NAME = "comentarios"

[version]
PORT = 8005
DB_COLLECTION_NAME = "versiones"

[auth]
PORT = 8080
GOOGLE_OAUTH_CLIENT_ID = ""
GOOGLE_OAUTH_CLIENT_SECRET = ""
GOOGLE_OAUTH_REDIRECT_URL = ""
JWT_SECRET = ""

[media]
PORT = 8081
CLOUDIFY_CLOUD_NAME = ""
CLOUDIFY_API_KEY = ""
CLOUDIFY_API_SECRET = ""
DB_COLLECTION_NAME = "media"
