services:
  api-gateway:
    build: ./gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - wiki-service
    networks:
      - app-network

  wiki-service:
    build: ./wiki
    container_name: wiki-service
    networks:
      - app-network

  # entry-service:
  #   build: ./entry
  #   container_name: entry-service
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
