services:
  api-gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./config.docker.toml:/app/config.toml
    environment:
      - DOCKER=true


  wiki-service:
    build: ./wiki
    networks:
      - app-network
    expose:
      - "8001"
    volumes:
      - ./config.docker.toml:/app/config.toml
    environment:
      - DOCKER=true

  entry-service:
    build: ./entry
    networks:
      - app-network
    expose:
      - "8002"
    volumes:
      - ./config.docker.toml:/app/config.toml
    environment:
      - DOCKER=true

  comment-service:
    build: ./comment
    networks:
      - app-network
    expose:
      - "8003"
    volumes:
      - ./config.docker.toml:/app/config.toml
    environment:
      - DOCKER=true

  version-service:
    build: ./version
    networks:
      - app-network
    expose:
      - "8005"
    volumes:
      - ./config.docker.toml:/app/config.toml
    environment:
      - DOCKER=true

  # auth-service:
  #   build: ./auth
  #   networks:
  #     - app-network
  #   expose:
  #     - "8080"
  #   volumes:
  #     - ./config.docker.toml:/app/config.toml
  #   environment:
  #     - DOCKER=true
  #     - DEEPL_API_KEY=4fa938db-960c-44fb-a509-f7ccfa7cd3c7:fx

  media-service:
    build: ./media
    networks:
      - app-network
    expose:
      - "8081"
    volumes:
      - ./config.docker.toml:/app/config.toml
    environment:
      - DOCKER=true

networks:
  app-network:
    driver: bridge
