services:
  api-gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - wiki-service
    networks:
      - app-network
    env_file:
        - ./.env.docker

  wiki-service:
    build: ./wiki
    networks:
      - app-network
    expose:
      - "8001"
    env_file:
      - ./.env.docker

  entry-service:
    build: ./entry
    networks:
      - app-network
    expose:
      - "8002"
    env_file:
      - ./.env.docker
      
networks:
  app-network:
    driver: bridge
